inherit_mode:
  merge:
    - Exclude
    - Include
Documentation:
  Enabled: false
Rails:
  Enabled: true
AllCops:
  UseCache: false
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']
Style/FrozenStringLiteralComment:
  Enabled: false